// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zyzgebbdsqlispmpgvev.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5emdlYmJkc3FsaXNwbXBndmV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIwMDA3MTksImV4cCI6MjA3NzU3NjcxOX0.ahUH6L7XrKjs9ZZ0OLLzrD53si9_g69Oy1FaiDqWXko";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});